# 🧱 NumPy Arrays

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Array%20Creation-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with different ways to create NumPy arrays — from fixed-value arrays to ranges and random values.

## 📚 Contents

| # | Function | Creates |
|---|----------|---------|
| 1 | `np.zeros()` | array filled with zeros |
| 2 | `np.ones()` | array filled with ones |
| 3 | `np.arange()` | evenly spaced values |
| 4 | `np.random.randint()` | random integers |
| 5 | `np.random.random()` | random decimals in `[0, 1)` |

---


In [1]:
import numpy as np

## 1️⃣ `np.zeros()`

`np.zeros()` creates a NumPy array filled with zeros.

```python
zeros_array = np.zeros(5)
```

```text
[0. 0. 0. 0. 0.]
```

The argument `5` specifies the number of elements.


In [2]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [3]:
print(zeros_array.shape)
print(zeros_array.size)
print(zeros_array.dtype)

(5,)
5
float64


> [!TIP]
> `np.zeros(n)` → creates an array of `n` zeros. Note the `dtype` defaults to `float64`, even though the values look like whole numbers.


## 2️⃣ `np.ones()`

`np.ones()` creates a NumPy array filled with ones.

```python
ones = np.ones(5)
```

```text
[1. 1. 1. 1. 1.]
```

The argument `5` specifies the number of elements.


In [4]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


> [!TIP]
> `np.ones(n)` → creates an array of `n` ones.


## 3️⃣ `np.arange()`

`np.arange()` creates a NumPy array containing evenly spaced values within a specified interval.

**Syntax**

```python
np.arange(start, stop, step)
```

- `start` — the starting value.
- `stop` — the ending boundary. This value is **not included**.
- `step` — the difference between consecutive values.


In [5]:
numbers = np.arange(5)
print(numbers)

[0 1 2 3 4]


In [6]:
numbers2 = np.arange(2, 10)
print(numbers2)

[2 3 4 5 6 7 8 9]


In [7]:
numbers3 = np.arange(2, 10, 2)
print(numbers3)

[2 4 6 8]


In [8]:
num = np.arange(10, 50, 5)
print(num)

[10 15 20 25 30 35 40 45]


> [!TIP]
> `np.arange(start, stop, step)` → generates values from `start` up to (but not including) `stop`, spaced by `step`. With one argument, `start` defaults to `0` and `step` to `1`.


## 4️⃣ `np.random.randint()`

`np.random.randint()` creates an array containing random integers from a specified range.

**Syntax**

```python
np.random.randint(low, high, size)
```

- `low` — the lowest possible value, included.
- `high` — the upper boundary, **not included**.
- `size` — the number or shape of values to generate.

The output changes every run since the values are randomly generated.


In [9]:
np.random.randint(1, 10, size=5)

array([2, 4, 5, 9, 9])

In [10]:
# 2D array
np.random.randint(1, 10, size=(3, 4))

array([[2, 2, 7, 7],
       [6, 8, 2, 2],
       [6, 8, 2, 5]])

> [!TIP]
> `np.random.randint(low, high, size)` → random integers from `low` (included) up to `high` (excluded). Pass a tuple like `size=(3, 4)` to generate a 2D array.


## 5️⃣ `np.random.random()`

`np.random.random()` generates random floating-point numbers between `0` (inclusive) and `1` (exclusive).

**Syntax**

```python
np.random.random(size)
```

- `size` — the number or shape of values to generate.
- Every value is `>= 0` and `< 1`.


In [11]:
random_numbers = np.random.random(5)
print(random_numbers)

[0.8399398  0.72317412 0.67862975 0.03861096 0.26924196]


In [12]:
random_numbers = np.random.random(10)
print(random_numbers)

[0.9015861  0.83616479 0.09449176 0.42394946 0.23686106 0.21643313
 0.76120896 0.69393806 0.27604732 0.62567384]


> [!TIP]
> `np.random.random(size)` → random decimals in `[0, 1)`. Pass a tuple, e.g. `size=(2, 3)`, for a 2D array.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
