# 🎯 NumPy Indexing and Slicing

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Indexing%20%26%20Slicing-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with accessing and extracting elements from NumPy arrays — indexing, slicing, and modifying values in both 1D and 2D arrays.

## 📚 Contents

| # | Topic |
|---|-------|
| 1 | Indexing |
| 2 | Negative indexing |
| 3 | Slicing |
| 4 | Slicing with `step` |
| 5 | Modifying array elements |
| 6 | 2D array indexing |
| 7 | Selecting rows / columns from a 2D array |
| 8 | 2D array slicing |
| 9 | Modifying multiple elements |
| 10 | Extra practice |

---


In [1]:
import numpy as np

## 1️⃣ Indexing

Indexing is used to access a specific element of a NumPy array.

NumPy uses **zero-based indexing** — the first element has index `0`.

```python
scores = np.array([83, 95, 40, 99, 18, 72])
scores[0]
```

```text
83
```


In [2]:
scores = np.array([83, 95, 40, 99, 18, 72])

print(scores[0])
print(scores[3])

83
99


In [3]:
print(scores[1])
print(scores[4])
print(scores[5])

95
18
72


> [!TIP]
> NumPy indexing starts from `0` — the first element is `array[0]`, not `array[1]`.


## 2️⃣ Negative Indexing

Negative indexing accesses elements from the end of the array. The last element is `-1`, the second-to-last is `-2`, and so on.

```python
scores = np.array([83, 95, 40, 99, 18, 72])
scores[-1]
```

```text
72
```


In [4]:
print(scores[-1])
print(scores[-2])

72
18


In [5]:
print(scores[-6])

83


> [!TIP]
> Positive indexing starts at `0` from the front; negative indexing starts at `-1` from the back. Since `scores` has 6 elements, `-6` wraps all the way around to the *same* element as `0` — the first one.


## 3️⃣ Slicing

Slicing extracts a portion of a NumPy array.

**Syntax**

```python
array[start:stop:step]
```

- `start` — starting index, included.
- `stop` — ending index, **not included**.
- `step` — the interval between elements.

```python
scores = np.array([83, 95, 40, 99, 18, 72])
scores[1:4]
```

```text
[95 40 99]
```

Indexes `1`, `2`, and `3` are included; index `4` is not.


In [6]:
print(scores[0:3])

[83 95 40]


### Omitting `stop`

If `stop` is omitted, the slice continues to the end of the array.

```python
scores[2:]
```
```text
[40 99 18 72]
```


In [7]:
print(scores[1:])

[95 40 99 18 72]


In [8]:
print(scores[:])

[83 95 40 99 18 72]


> [!TIP]
> `array[start:]` → starts at `start`, continues to the end. `array[:]` → a full copy of the array, start to end.


## 4️⃣ Slicing with `step`

`step` sets how many positions to move between selected elements.

```python
array[start:stop:step]
```

```python
scores[0:6:2]
```
```text
[83 40 18]
```

Every second element is selected.


In [9]:
print(scores[0:8:2])

[83 40 18]


> [!NOTE]
> `scores` only has 6 elements, but `stop=8` above doesn't raise an error — NumPy automatically clips a slice's `stop` to the array's length. The result is identical to `scores[0:6:2]`.


In [10]:
print(scores[::2])  # without start, stop

[83 40 18]


In [11]:
print(scores[::-1])

[72 18 99 40 95 83]


> [!TIP]
> `step=2` → take every second element. `step=-1` with no `start`/`stop` reverses the whole array.


## 5️⃣ Modifying Array Elements

NumPy lets you change an element by assigning a new value to its index.

```python
scores[2] = 100
print(scores)
```
```text
[83 95 100 99 18 72]
```


In [12]:
scores = np.array([83, 95, 40, 99, 18, 72])

scores[2] = 100
print(scores)

[ 83  95 100  99  18  72]


In [13]:
scores[4] = 80
print(scores)

[ 83  95 100  99  80  80]


> [!TIP]
> `array[index] = new_value` → changes the value at that index in place. `scores[5]` still holds `72` here — only index `4` was reassigned to `80`.


## 6️⃣ 2D Array Indexing

A 2D array has rows and columns. Access a single element with two indexes:

```python
array[row, column]
```

Both start from `0`.

```python
matrix[0, 1]
```
```text
20
```


In [14]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
print(matrix[2, 1])

80


> [!TIP]
> `array[row, column]` → accesses one element in a 2D array. The first index picks the row, the second picks the column.


## 7️⃣ Selecting Rows and Columns from a 2D Array

An entire **row** is selected with a single index:

```python
matrix[1]
```
```text
[40 50 60]
```

An entire **column** is selected with `:` for rows and the column index:

```python
matrix[:, 1]
```
```text
[20 50 80]
```


In [16]:
print(matrix[2])

[70 80 90]


In [17]:
print(matrix[:, 1])

[20 50 80]


In [18]:
print(matrix[:, 2])

[30 60 90]


> [!TIP]
> `array[row]` → an entire row. `array[:, column]` → an entire column, where `:` means "all rows."


## 8️⃣ 2D Array Slicing

Slicing selects multiple rows and columns at once:

```python
array[row_start:row_stop, column_start:column_stop]
```

`stop` is not included, just like 1D slicing.

```python
matrix[0:2, 1:3]
```
```text
[[20 30]
 [50 60]]
```

This selects rows `0`–`1` and columns `1`–`2`.


In [19]:
print(matrix[0:2, 1:3])

[[20 30]
 [50 60]]


In [20]:
print(matrix[1:3, 1:3])

[[50 60]
 [80 90]]


> [!TIP]
> For a 2D array, the first slice picks rows and the second picks columns — `array[rows, columns]`.


## 9️⃣ Modifying Multiple Elements

Slicing can modify several elements at once.

```python
matrix[0, :] = 100
```

This sets every element in the first row to `100`:

```text
[[100 100 100]
 [ 40  50  60]
 [ 70  80  90]]
```

`:` selects every column in that row.


In [21]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matrix[0, :] = 100
print(matrix)

[[100 100 100]
 [ 40  50  60]
 [ 70  80  90]]


In [22]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matrix[2, :] = 0
print(matrix)

[[10 20 30]
 [40 50 60]
 [ 0  0  0]]


> [!TIP]
> `array[row, :] = value` → overwrites every element in that row. The same works for a column with `array[:, col] = value`.


## 🧪 Extra Practice — Combining Indexing and Slicing

A few more reads on a fresh copy of `matrix`, mixing single-element indexing, row/column slicing, and reversed selections.


In [23]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix[1, 1])

50


In [24]:
print(matrix[0])

[10 20 30]


In [25]:
print(matrix[0:3, 2:])

[[30]
 [60]
 [90]]


> [!NOTE]
> `matrix[:, 2]` and `matrix[:, 2:]` look similar but return different shapes: a single-index column collapses to 1D, while a *sliced* column keeps its 2D shape.


In [26]:
print(matrix[:, 2])   # shape (3,)  — 1D

[30 60 90]


In [27]:
matrix[:, 2:]         # shape (3, 1) — 2D

array([[30],
       [60],
       [90]])

In [28]:
print(matrix[1:, 1:])

[[50 60]
 [80 90]]


> [!TIP]
> `array[:, col]` → a 1D array of that column's values. `array[:, col:]` → the same values, but kept as a 2D column.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
