# ➗ NumPy Array Operations

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Math%20%26%20Comparison-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with mathematical and comparison operations on NumPy arrays — arithmetic, comparisons, Boolean filtering, vectorization, and broadcasting.

## 📚 Contents

| # | Topic |
|---|-------|
| 1 | Arithmetic operations (overview) |
| 2 | Addition |
| 3 | Subtraction |
| 4 | Multiplication |
| 5 | Division |
| 6 | Power |
| 7 | Operations with a scalar |
| 8 | Vectorization |
| 9 | Broadcasting |
| 10 | Comparison operations |
| 11 | Boolean array filtering |
| 12 | Multiple conditions with `&` |
| 13 | Multiple conditions with `\|` |

---


## 1️⃣ Arithmetic Operations

NumPy performs arithmetic operations directly on arrays. When two arrays share the same shape, the operation runs **element by element**.

| Operator | Meaning |
|----------|---------|
| `+` | addition |
| `-` | subtraction |
| `*` | multiplication |
| `/` | division |
| `**` | power |


In [1]:
import numpy as np

> [!TIP]
> NumPy performs arithmetic operations element by element — no loop required. The sections below walk through each operator individually.


## 2️⃣ Addition

The `+` operator adds two arrays element by element.

```python
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
a + b
```
```text
[11 22 33]
```


In [2]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


In [3]:
a = np.array([5, 10, 15])
b = np.array([2, 4, 6])

print(a + b)

[ 7 14 21]


> [!TIP]
> Each element is added to the element at the same position in the other array.


## 3️⃣ Subtraction

The `-` operator subtracts two arrays element by element.

```python
prices = np.array([100, 200, 300])
discounts = np.array([10, 20, 30])
prices - discounts
```
```text
[ 90 180 270]
```


In [4]:
prices = np.array([100, 200, 300])
discounts = np.array([10, 20, 30])

print(prices - discounts)

[ 90 180 270]


> [!TIP]
> Just like addition, subtraction lines up elements at matching positions.


## 4️⃣ Multiplication

The `*` operator performs **element-wise** multiplication — not matrix multiplication.

```python
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
a * b
```
```text
[10 18 28]
```


In [5]:
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

print(a * b)

[10 18 28]


In [6]:
a = np.array([10, 20, 30])
b = np.array([2, 3, 4])

print(a * b)

[ 20  60 120]


> [!TIP]
> `*` multiplies matching elements, not rows by columns like true matrix multiplication (that's `@` or `np.matmul()`).


## 5️⃣ Division

The `/` operator performs element-wise division.

```python
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])
a / b
```
```text
[5. 5. 6.]
```


In [7]:
a = np.array([20, 40, 60])
b = np.array([2, 4, 5])

print(a / b)

[10. 10. 12.]


> [!TIP]
> Division usually produces floating-point values, even when the inputs are integers.


## 6️⃣ Power

The `**` operator raises each element to a specified power.

```python
numbers = np.array([2, 3, 4])
numbers ** 2
```
```text
[ 4  9 16]
```

```text
2² = 4
3² = 9
4² = 16
```


In [8]:
numbers = np.array([2, 4, 5])

print(numbers ** 3)

[  8  64 125]


> [!TIP]
> `array ** n` → raises every element to the power of `n`.


## 7️⃣ Operations with a Scalar

NumPy also supports arithmetic between an array and a single number (a **scalar**) — the operation is applied to every element.

```python
numbers = np.array([10, 20, 30])
numbers + 5
```
```text
[15 25 35]
```

```python
numbers * 2
```
```text
[20 40 60]
```


In [9]:
numbers = np.array([10, 20, 30])

print(numbers + 10)

[20 30 40]


> [!TIP]
> NumPy automatically applies a scalar operation to every element — this is the simplest form of **broadcasting** (see below).


## 8️⃣ Vectorization

Vectorization means performing an operation on an entire array without writing an explicit loop.

```python
numbers = np.array([10, 20, 30])
numbers * 2
```
```text
[20 40 60]
```

Instead of looping over each element, NumPy applies the operation to the whole array at once.


In [10]:
numbers = np.array([5, 10, 15, 20])

print(numbers * 3)

[15 30 45 60]


> [!TIP]
> Vectorization makes array operations concise **and** efficient — NumPy runs the loop in fast, compiled C code instead of Python.


## 9️⃣ Broadcasting

Broadcasting is how NumPy handles arithmetic between arrays of **different shapes**, by automatically stretching the smaller one to match — without actually copying data.

The scalar example above (`numbers + 10`) is the simplest case: a single number is "broadcast" across every element.

Broadcasting also works between arrays of different shapes, as long as their shapes are compatible. For example, a 1D array can be added to every row of a 2D array:

```python
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
row = np.array([10, 20, 30])

matrix + row
```
```text
[[11 22 33]
 [14 25 36]]
```

`row` has shape `(3,)`, matching the number of columns in `matrix`, so NumPy applies it to each of the 2 rows.


In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
row = np.array([10, 20, 30])

print(matrix + row)

[[11 22 33]
 [14 25 36]]


> [!TIP]
> Broadcasting rules: shapes are compared from the right; dimensions match if they're equal or one of them is `1`. A scalar (shape `()`) and a `(3,)` array added to a `(2, 3)` matrix both work by this rule.


## 🔟 Comparison Operations

NumPy compares each element of an array against a value or another array.

| Operator | Meaning |
|----------|---------|
| `>` | greater than |
| `<` | less than |
| `>=` | greater than or equal to |
| `<=` | less than or equal to |
| `==` | equal to |
| `!=` | not equal to |

The result is a **Boolean array** — `True`/`False` for each element.

```python
scores = np.array([45, 80, 65, 90, 30])
scores > 60
```
```text
[False  True  True  True False]
```


In [12]:
temperatures = np.array([18, 25, 31, 15, 28, 35])

print(temperatures > 30)

[False False  True False False  True]


> [!TIP]
> Comparison operators return a Boolean array, checking each element independently.


## 1️⃣1️⃣ Boolean Array Filtering

Boolean indexing selects elements from an array based on a condition.

```python
scores = np.array([45, 80, 65, 90, 30])
scores[scores > 60]
```
```text
[80 65 90]
```

NumPy first builds a Boolean condition (`scores > 60`), then uses it to keep only the elements where the condition is `True`.


In [13]:
temperatures = np.array([18, 25, 31, 15, 28, 35])

print(temperatures[temperatures > 30])

[31 35]


> [!TIP]
> `array[condition]` → selects only the elements that satisfy the condition.


## 1️⃣2️⃣ Multiple Conditions with `&`

`&` combines conditions where **all of them must be True**.

```python
scores = np.array([45, 60, 75, 80, 90])
scores[(scores > 60) & (scores < 90)]
```
```text
[75 80]
```

An element must be both greater than `60` **and** less than `90`.


In [14]:
temperatures = np.array([15, 22, 28, 31, 35, 18, 25])

print(temperatures[(temperatures > 30) & (temperatures < 35)])

[31]


> [!IMPORTANT]
> Wrap each condition in its own parentheses: `array[(condition1) & (condition2)]`. Without them, Python's operator precedence raises an error.


## 1️⃣3️⃣ Multiple Conditions with `|`

`|` combines conditions where **at least one must be True**.

```python
scores = np.array([45, 60, 75, 80, 90])
scores[(scores < 50) | (scores > 85)]
```
```text
[45 90]
```

An element is selected if it's less than `50` **or** greater than `85`.


In [15]:
temperatures = np.array([15, 22, 28, 31, 35, 18, 25])

print(temperatures[(temperatures < 20) | (temperatures > 30)])

[15 31 35 18]


> [!IMPORTANT]
> Same rule as with `&` — each condition needs its own parentheses: `array[(condition1) | (condition2)]`.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
