# 🔄 NumPy Reshaping

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Reshaping-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with reshaping NumPy arrays — changing dimensions, flattening, raveling, and transposing.

## 📚 Contents

| # | Topic |
|---|-------|
| 1 | `reshape()` |
| 2 | `reshape()` with `-1` |
| 3 | `flatten()` |
| 4 | `ravel()` |
| 5 | `flatten()` vs `ravel()` — copy vs. view |
| 6 | Mini practice |
| 7 | `transpose()` |

---


## 1️⃣ `reshape()`

`reshape()` changes the shape of a NumPy array without changing its data.

The **total number of elements must stay the same**. For example, an array with 6 elements can be reshaped into:

- `2 × 3`
- `3 × 2`
- `1 × 6`
- `6 × 1`


In [1]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])

print(numbers.shape)

(6,)


In [2]:
numbers_2d = numbers.reshape(2, 3)

print(numbers_2d)
print(numbers_2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Reshaping the same 6 elements into a different shape (`3 × 2`) rearranges them differently:


In [3]:
numbers = np.array([10, 20, 30, 40, 50, 60])

print(numbers.reshape(3, 2))

[[10 20]
 [30 40]
 [50 60]]


In [4]:
numbers = np.array([10, 20, 30, 40, 50, 60])

print(numbers.reshape(2, 3))

[[10 20 30]
 [40 50 60]]


Reshaping isn't limited to 2D — a 12-element array can become a 3D array, e.g. `2 × 2 × 3`:


In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

numbers_3d = numbers.reshape(2, 2, 3)

print(numbers_3d)
print(numbers_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


> [!TIP]
> `array.reshape(new_shape)` → rearranges the same data into a new shape. The product of the new dimensions must equal the array's total element count — `2 × 2 × 3 = 12`, matching the original `(12,)` array.


## 2️⃣ `reshape()` with `-1`

When you don't know (or don't want to compute) the size of one dimension, pass `-1` for it — NumPy calculates that dimension automatically from the total element count.

```python
numbers = np.array([1, 2, 3, 4, 5, 6])
numbers.reshape(2, -1)
```

Since the array has 6 elements and the first dimension is fixed at `2`, NumPy infers the second dimension: `6 / 2 = 3`, so the result has shape `(2, 3)`.


In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6])

result = numbers.reshape(2, -1)

print(result)
print(result.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
numbers = np.arange(1, 13)

result = numbers.reshape(3, -1)

print(result)
print(result.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


> [!TIP]
> `-1` works with `reshape()` as long as only **one** dimension is unknown — NumPy still enforces that the total element count matches, it just does the division for you.


## 3️⃣ `flatten()`

`flatten()` converts a multi-dimensional array into a one-dimensional array. It always returns a **new copy** of the data.


In [8]:
numbers_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

numbers_1d = numbers_3d.flatten()

print(numbers_1d)
print(numbers_1d.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


> [!TIP]
> `array.flatten()` → collapses any number of dimensions into a single 1D array, always as an independent copy.


## 4️⃣ `ravel()`

`ravel()` also converts a multi-dimensional array into a one-dimensional array — but it usually returns a **view** of the original array rather than a copy, when possible.


In [9]:
numbers_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

numbers_1d = numbers_3d.ravel()

print(numbers_1d)
print(numbers_1d.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


> [!TIP]
> `array.ravel()` → same result as `flatten()` on the surface, but the underlying memory behavior is different — see the comparison below.


## 5️⃣ `flatten()` vs `ravel()` — Copy vs. View

Both functions flatten an array to 1D, but they handle the original array's memory differently:

| | `flatten()` | `ravel()` |
|---|---|---|
| Returns | a new **copy** | a **view**, when possible |
| Editing the result | does **not** affect the original | **may** affect the original |
| Best for | an independent 1D array | memory efficiency, no copy needed |

### `flatten()` — editing the copy leaves the original untouched


In [10]:
a = np.array([[1, 2], [3, 4]])

b = a.flatten()

b[0] = 100

print(a)
print(b)

[[1 2]
 [3 4]]
[100   2   3   4]


### `ravel()` — editing the view changes the original


In [11]:
a = np.array([[1, 2], [3, 4]])

b = a.ravel()

b[0] = 100

print(a)
print(b)

[[100   2]
 [  3   4]]
[100   2   3   4]


A second example with a `(2, 3)` array makes the same contrast clear side by side:


In [12]:
numbers = np.array([[1, 2, 3], [4, 5, 6]])

flat = numbers.flatten()
flat[0] = 100

print("Original:")
print(numbers)

print("Flatten:")
print(flat)

Original:
[[1 2 3]
 [4 5 6]]
Flatten:
[100   2   3   4   5   6]


In [13]:
numbers = np.array([[1, 2, 3], [4, 5, 6]])

raveled = numbers.ravel()
raveled[0] = 100

print("Original:")
print(numbers)

print("Ravel:")
print(raveled)

Original:
[[100   2   3]
 [  4   5   6]]
Ravel:
[100   2   3   4   5   6]


> [!IMPORTANT]
> **Remember:** use `flatten()` when you need an independent copy; use `ravel()` when you want a 1D view and memory efficiency matters.


## 🧪 6️⃣ Mini Practice — Reshaping

Combining `reshape()`, `flatten()`, and `ravel()` on one array:


In [14]:
numbers = np.arange(1, 13)

array_2d = numbers.reshape(4, 3)
print(array_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
flat = array_2d.flatten()

print(flat)
print(flat.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [16]:
raveled = array_2d.ravel()

print(raveled)
print(raveled.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## 7️⃣ `transpose()`

`transpose()` swaps the rows and columns of an array. For a 2D array, rows become columns and columns become rows — the shape changes from `(rows, columns)` to `(columns, rows)`.


In [17]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(array_2d)

[[1 2 3]
 [4 5 6]]


In [18]:
transposed = array_2d.transpose()

print(transposed)
print(transposed.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [19]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

In [20]:
transposed = matrix.transpose()
print(transposed)

[[10 40]
 [20 50]
 [30 60]]


> [!TIP]
> `array.transpose()` (or the shorthand `array.T`) flips a `(rows, columns)` array into `(columns, rows)` — element `[i, j]` moves to `[j, i]`.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
