# 🧩 NumPy Joining Arrays

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Joining%20Arrays-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with joining NumPy arrays — concatenating along an axis, and stacking vertically or horizontally.

## 📚 Contents

| # | Function | Joins |
|---|----------|-------|
| 1 | `np.concatenate()` | along a chosen axis |
| 2 | `np.vstack()` | vertically (more rows) |
| 3 | `np.hstack()` | horizontally (more columns) |

---


## 1️⃣ `np.concatenate()`

`np.concatenate()` joins two or more NumPy arrays into one.

For 1D arrays, it joins them along the only axis they have.


In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


In [2]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.concatenate((a, b))

print(result)

[10 20 30 40 50 60]


### Concatenating 2D arrays along an axis

For 2D arrays, `axis` controls the direction of the join:

- `axis=0` (the default) — stacks along rows, adding more rows.
- `axis=1` — stacks along columns, adding more columns.


In [3]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.concatenate((a, b))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.concatenate((a, b), axis=1)

print(result)

[[1 2 5 6]
 [3 4 7 8]]


> [!TIP]
> `np.concatenate((a, b))` defaults to `axis=0`. Pass `axis=1` to join side by side instead of stacking on top of each other — both arrays must have compatible shapes along the axis you're *not* joining on.


## 2️⃣ `np.vstack()`

`np.vstack()` joins arrays **vertically**, stacking them on top of each other and increasing the number of rows.

For 2D arrays, it works the same as `np.concatenate(..., axis=0)`.


In [5]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.vstack((a, b))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
a = np.array([
    [10, 20],
    [30, 40]
])

b = np.array([
    [50, 60],
    [70, 80]
])

result = np.vstack((a, b))

print(result)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


> [!TIP]
> `np.vstack((a, b))` → same result as `np.concatenate((a, b), axis=0)`, but arguably reads more clearly when the intent is specifically "stack these vertically."


## 3️⃣ `np.hstack()`

`np.hstack()` joins arrays **horizontally**, placing them side by side and increasing the number of columns.

For 2D arrays, it works the same as `np.concatenate(..., axis=1)`.


In [7]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.hstack((a, b))

print(result)

[[1 2 5 6]
 [3 4 7 8]]


> [!TIP]
> `np.hstack((a, b))` → same result as `np.concatenate((a, b), axis=1)`. Together, `vstack`/`hstack` are shorthand for the two most common concatenation directions.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
