# 🔎 NumPy Searching Arrays

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Searching%20Arrays-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with searching NumPy arrays — finding indices with `np.where()`, conditional replacement, and locating insertion points with `np.searchsorted()`.

## 📚 Contents

| # | Topic |
|---|-------|
| 1 | `np.where()` — finding indices |
| 2 | `np.where()` — replacing values |
| 3 | `np.searchsorted()` |
| 4 | Using `searchsorted()` to insert a value |

---


## 1️⃣ `np.where()` — Finding Indices

`np.where()` returns the indices of elements that satisfy a given condition — useful for finding *where* matching elements live, not just which ones.


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 25)

print(result)

(array([2, 3, 4]),)


In [2]:
arr = np.array([10, 60, 30, 80, 40, 90, 20])

result = np.where(arr > 50)

print(result)

(array([1, 3, 5]),)


> [!TIP]
> `np.where(condition)` → returns a tuple containing an array of matching indices — that's why the output looks like `(array([...]),)` rather than a plain array. Use `result[0]` to get just the index array.


## 2️⃣ `np.where()` — Replacing Values

With three arguments, `np.where(condition, x, y)` returns `x` where the condition is `True` and `y` where it's `False` — element by element.


In [3]:
arr = np.array([10, 60, 30, 80, 40, 90, 20])

result = np.where(arr > 50, 1, 0)

print(result)

[0 1 0 1 0 1 0]


In [4]:
arr = np.array([30, 70, 45, 90, 55, 20])

result = np.where(arr >= 50, "High", "Low")
print(result)

['Low' 'High' 'Low' 'High' 'High' 'Low']


> [!TIP]
> `np.where(condition, x, y)` → a vectorized if/else. It works with numbers, strings, or even other arrays for `x` and `y`.


## 3️⃣ `np.searchsorted()`

`np.searchsorted()` finds the index where a value should be inserted into a **sorted** array to keep it sorted.


In [5]:
arr = np.array([10, 20, 30, 40, 50])

result = np.searchsorted(arr, 35)

print(result)

3


In [6]:
arr = np.array([10, 20, 30, 40, 50])

result = np.searchsorted(arr, 25)

print(result)

2


In [7]:
arr = np.array([10, 20, 30, 40, 50])

result = np.searchsorted(arr, 40)

print(result)

3


> [!NOTE]
> When the value already exists in the array (like `40` above), `np.searchsorted()` defaults to `side='left'` — it returns the index *before* the existing match, so inserting there would place the new value ahead of the equal one. Pass `side='right'` to insert after it instead.


> [!TIP]
> `np.searchsorted(array, value)` → the index that keeps `array` sorted after inserting `value`. It relies on binary search, so it's fast even for large sorted arrays.


## 4️⃣ Using `searchsorted()` to Insert a Value

Combining `np.searchsorted()` with `np.insert()` inserts a value at exactly the right position to keep the array sorted.


In [8]:
arr = np.array([10, 20, 30, 40, 50])

index = np.searchsorted(arr, 25)
result = np.insert(arr, index, 25)

print(result)

[10 20 25 30 40 50]


> [!TIP]
> `np.insert(array, index, value)` → returns a **new** array with `value` placed at `index`; the original array is left unchanged. Pairing it with `searchsorted()` is a common pattern for inserting into a sorted array without re-sorting from scratch.


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
