# 🔀 NumPy Sorting Arrays

![Python](https://img.shields.io/badge/Python-3.10+-3776AB?style=flat-square&logo=python&logoColor=white)
![NumPy](https://img.shields.io/badge/NumPy-Sorting%20Arrays-013243?style=flat-square&logo=numpy&logoColor=white)
![Status](https://img.shields.io/badge/Status-Complete-2ea44f?style=flat-square)

Hands-on practice with sorting NumPy arrays — `np.sort()` on 1D and 2D arrays, and finding sort order with `np.argsort()`.

## 📚 Contents

| # | Topic |
|---|-------|
| 1 | `np.sort()` — 1D arrays |
| 2 | `np.sort()` — 2D arrays |
| 3 | `np.argsort()` |
| 4 | Using `argsort()` to reorder an array |

---


## 1️⃣ `np.sort()` — 1D Arrays

`np.sort()` returns a **sorted copy** of a NumPy array — the original array is left unchanged. By default, values are sorted in ascending order.


In [1]:
import numpy as np

arr = np.array([40, 10, 30, 20, 50])

result = np.sort(arr)

print(result)

[10 20 30 40 50]


In [2]:
arr = np.array([70, 20, 90, 40, 10, 60])

result = np.sort(arr)

print(result)

[10 20 40 60 70 90]


> [!TIP]
> `np.sort(array)` → a new sorted array. If you need the original array itself sorted in place, use the `.sort()` method instead (e.g. `arr.sort()`), which returns `None` and mutates `arr` directly.


## 2️⃣ `np.sort()` — 2D Arrays

For a 2D array, `np.sort()` sorts **each row independently** by default (`axis=-1`, the last axis) — it doesn't sort the array as one flat sequence.


In [3]:
arr = np.array([
    [30, 10, 20],
    [60, 40, 50]
])

result = np.sort(arr)

print(result)

[[10 20 30]
 [40 50 60]]


> [!TIP]
> Each row is sorted on its own — `[30, 10, 20]` becomes `[10, 20, 30]` and `[60, 40, 50]` becomes `[40, 50, 60]`, independently of each other. Pass `axis=0` to sort each *column* instead, or `axis=None` to sort the whole array as if it were flattened.


## 3️⃣ `np.argsort()`

`np.argsort()` returns the **indices** that would sort an array, rather than the sorted values themselves — it tells you the original position each value would move from.


In [4]:
arr = np.array([40, 10, 30, 20])

result = np.argsort(arr)

print(result)

[1 3 2 0]


The result `[1, 3, 2, 0]` means: the smallest value is at index `1` (`10`), the next-smallest is at index `3` (`20`), then index `2` (`30`), then index `0` (`40`).


In [5]:
arr = np.array([50, 20, 40, 10, 30])

result = np.argsort(arr)

print(result)

[3 1 4 2 0]


> [!TIP]
> `np.argsort(array)` → index positions in sort order, not values. Read it as "which index comes first, second, third..." once the array is sorted.


## 4️⃣ Using `argsort()` to Reorder an Array

`argsort()`'s real usefulness shows up when the indices are used to reorder the array itself, or to reorder a *related* array by the same order.


In [6]:
arr = np.array([40, 10, 30, 20])

indices = np.argsort(arr)
sorted_arr = arr[indices]

print(indices)
print(sorted_arr)

[1 3 2 0]
[10 20 30 40]


> [!TIP]
> `array[np.argsort(array)]` produces the same result as `np.sort(array)` — but because `argsort()` gives you the *indices*, you can also apply them to a second, related array to keep both in sync (e.g. sorting a list of names by a matching list of scores).


---

✨ *Practice notebook — built while learning NumPy fundamentals* ✨
